repos:
-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      exclude: src/filters.py
- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
    - id: isort
      name: isort (python)
    - id: isort
      name: isort (cython)
      types: [cython]
    - id: isort
      name: isort (pyi)
      types: [pyi]
- repo: local
  hooks:
    - id: wily
      name: wily
      entry: wily diff
      verbose: true
      language: python
      additional_dependencies: [wily]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: ''  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
repos:
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.3'  # or any later Vulture version
    hooks:
      - id: vulture
